import sys, os, pdb

#sys.path.insert(0, os.path.abspath(os.path.join('..', '..', '/cirrus_stream')))

sys.path.append(os.path.abspath('sphinxext'))

# -- Path setup --------------------------------------------------------------

# Set the software project root dirs
cirrus_root = os.path.join(os.path.dirname(os.path.dirname(os.getcwd())), "cirrus_stream/")
test_root = os.path.join(os.path.dirname(os.path.dirname(os.getcwd())), "cirrus_stream/tests/")
stream_root = os.path.join(os.path.dirname(os.path.dirname(os.getcwd())), "cirrus_stream/stream/")
monitoring_root = os.path.join(os.path.dirname(os.path.dirname(os.getcwd())), "cirrus_stream/monitoring/")
etl_root = os.path.join(os.path.dirname(os.path.dirname(os.getcwd())), "cirrus_stream/etl/")
# Insert the project root dir as the first element in the PYTHONPATH.
# This lets us ensure that the source package is imported, and that its
# version is used.
sys.path.append(cirrus_root)
sys.path.append(test_root)
sys.path.append(stream_root)
sys.path.append(monitoring_root)
sys.path.append(etl_root)

# Function to append system path with all info necessary to populate docstrings

for x in os.walk('cirrus_stream'):
    sys.path.insert(0, x[0])

# -- Project information -----------------------------------------------------
project = 'CirrusStream'
copyright = 'YouSolar Engineering, 2024'
author = 'Brett Nelson, Yousolar Engineering'

# The full version, including alpha/beta/rc tags
version = '1.0.0'
release = 'beta'

# -- General configuration ---------------------------------------------------
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.githubpages',
    'sphinx.ext.mathjax',
    'sphinx.ext.autosectionlabel'

]

# Options for Napolean extension
napoleon_google_docstring = False
napoleon_numpy_docstring = True


#todo_include_todos = True

# tell autodoc which imports to mock
autodoc_mock_imports = [
    'pandas', 'numpy', 'paramiko', 'scp', 'pyarrow', 'setuptools', 'sphinx', 'sphinx_rtd_theme'
]


# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'
# source parser = 'md'
source_parsers = {'.md': '.rst'}
# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
#html_logo = '/_static/cirrus_2.png'
#html_theme_options = {'logo_only': False}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
#html_static_path = []
